name: Prevent Merge on Blocked PRs

on:
  workflow_call:
    inputs:
      blocking_labels:
        description: 'Comma-separated list of labels that should block PR merging'
        required: true
        type: string
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize, reopened]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for blocking labels
        uses: actions/github-script@v7
        with:
          script: |
            const blockingLabels = "${{ inputs.blocking_labels }}".split(',').map(label => label.trim());
            const prNumber = context.payload.pull_request.number;
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });
            
            const foundBlockingLabels = labels.filter(label => 
              blockingLabels.includes(label.name)
            );
            
            if (foundBlockingLabels.length > 0) {
              const foundLabelNames = foundBlockingLabels.map(label => label.name).join(', ');
              core.setFailed(`PR cannot be merged because it has the following blocking label(s): "${foundLabelNames}"`);
            }