name: Prevent Merge on Blocked PRs

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize, reopened]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "B2 - Blocked" label
        uses: actions/github-script@v7
        with:
          script: |
            const labelToBlock = "B2 - Blocked";
            const prNumber = context.payload.pull_request.number;

            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber
            });

            const hasBlockLabel = labels.some(label => label.name === labelToBlock);

            if (hasBlockLabel) {
              core.setFailed(`PR cannot be merged because it has the label "${labelToBlock}"`);
            }